In [1]:
import numpy as np

In [2]:
#从 arr 中提取所有的奇数
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_arr = arr[arr % 2 == 1]
print(odd_arr)

[1 3 5 7 9]


In [3]:
#将arr中的所有奇数替换为-1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
#将arr中的所有奇数替换为-1，而不改变arr。
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
#将一维数组转换为2行的2维数组
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
#垂直堆叠数组a和数组b
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#第一种
res1 = np.concatenate([a,b], axis=0)
print(res1)
#第二种
res2 = np.vstack([a,b])
print(res2)
#第三种
res3 = np.r_[a,b]
print(res3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
#将数组a和数组b水平堆叠。
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#第一种
res1 = np.concatenate([a,b], axis=1)
print(res1)
#第二种
res2 = np.hstack([a,b])
print(res2)
#第三种
res3 = np.c_[a,b]
print(res3)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
