In [2]:
import numpy as np

In [7]:
my_array = np.array([1, 2, 3, 4, 5])

In [8]:
print(my_array)

[1 2 3 4 5]


In [9]:
print(my_array[2])

3


In [10]:
my_array[0]=56
print(my_array)

[56  2  3  4  5]


In [14]:
#创建一个长度为5的数组，所有元素值为0
my_new_array = np.zeros((5))
print(my_new_array)

[0. 0. 0. 0. 0.]


In [17]:
#创建所有元素值为随机数的数组
my_random_array = np.random.random((5))
print(my_random_array)

[0.49977184 0.49723837 0.59322265 0.03277092 0.15729141]


In [19]:
#创建二维数组
my_2d_array = np.zeros((2, 3))
print(my_2d_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
my_2d_array_new = np.ones((2, 4))
print(my_2d_array_new)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
my_2d_array_new[0][2]=12
print(my_2d_array_new)

[[ 1.  1. 12.  1.]
 [ 1.  1.  1.  1.]]


In [3]:
my_array = np.array([[4, 5], [6, 1]])
print(my_array)

[[4 5]
 [6 1]]


In [4]:
print(my_array[0][1])

5


In [5]:
print(my_array.shape)

(2, 2)


In [6]:
print(my_array[:1])

[[4 5]]


In [7]:
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
b = np.array([[5.0, 6.0], [7.0, 8.0]]) 
sum = a + b 
difference = a - b 
product = a * b 
quotient = a / b 

In [10]:
print("sum=\n",sum)

sum=
 [[ 6.  8.]
 [10. 12.]]


In [12]:
print("difference=\n",difference)

difference=
 [[-4. -4.]
 [-4. -4.]]


In [13]:
print("product=\n",product)

product=
 [[ 5. 12.]
 [21. 32.]]


In [14]:
print("quotient=\n",quotient)

quotient=
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
matrix_product = a.dot(b) 
print("matrix_product=",matrix_product)

matrix_product= [[19. 22.]
 [43. 50.]]
