In [1]:
import numpy as np

In [2]:
#从 arr 中提取所有的奇数
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_arr = arr[arr % 2 == 1]
print(odd_arr)

[1 3 5 7 9]


In [3]:
#将arr中的所有奇数替换为-1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
#将arr中的所有奇数替换为-1，而不改变arr。
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
#将一维数组转换为2行的2维数组
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
#垂直堆叠数组a和数组b
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#第一种
res1 = np.concatenate([a,b], axis=0)
print(res1)
#第二种
res2 = np.vstack([a,b])
print(res2)
#第三种
res3 = np.r_[a,b]
print(res3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
#将数组a和数组b水平堆叠。
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#第一种
res1 = np.concatenate([a,b], axis=1)
print(res1)
#第二种
res2 = np.hstack([a,b])
print(res2)
#第三种
res3 = np.c_[a,b]
print(res3)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [4]:
#创建以下模式而不使用硬编码。只使用numpy函数和下面的输入数组a
a = np.array([1,2,3])
# 输出> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
print(a)
rep_arr = np.repeat(a,3)
rep_tail = np.tile(a,3)
print(rep_arr)
print(rep_tail)
result = np.r_[rep_arr,rep_tail]
print(result)

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [5]:
#获取数组a和数组b之间的公共项
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [6]:
#从数组a中删除数组b中的所有项
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [10]:
#获取a和b元素匹配的位置
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [22]:
#获取5到10之间的所有项目
a = np.arange(15)
#第一种
index = np.where((a>=5) & (a<=10))
result_array = a[index]
print(result_array)
#第二种
index = np.where(np.logical_and(a>=5,a<=10))
result_array = a[index]
print(result_array)
#第三种
result_array = a[(a>=5) & (a<=10)]
print(result_array)

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [23]:
#转换适用于两个标量的函数maxx，以处理两个数组
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
new_func = np.vectorize(maxx,[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result_array = new_func(a,b)
print(result_array)

[6. 7. 9. 8. 9. 7. 5.]


In [29]:
#在数组arr中交换列1和2
arr = np.arange(9).reshape(3,3)
print(arr)
result_array = arr[:,[1,0,2]]
print(result_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [27]:
#交换数组arr中的第1和第2行
arr = np.arange(9).reshape(3,3)
print(arr)
result_array = arr[[1,0,2],:]
print(result_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [30]:
#反转二维数组arr的行
arr = np.arange(9).reshape(3,3)
result_array = arr[::-1]
print(result_array)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [31]:
#反转二维数组arr的列
arr = np.arange(9).reshape(3,3)
result_array = arr[:,::-1]
print(result_array)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [32]:
#只打印或显示numpy数组rand_arr的小数点后3位
rand_arr = np.random.random((5,3))
print(rand_arr)
#set_printoptions设置输出样式
np.set_printoptions(precision=3)
print(rand_arr)

[[0.41929708 0.1841082  0.93328388]
 [0.43413862 0.31824767 0.71969152]
 [0.58931818 0.37012339 0.2079629 ]
 [0.35507993 0.6690454  0.78762693]
 [0.96644331 0.1383715  0.67131889]]
[[0.419 0.184 0.933]
 [0.434 0.318 0.72 ]
 [0.589 0.37  0.208]
 [0.355 0.669 0.788]
 [0.966 0.138 0.671]]


In [36]:
#通过e式科学记数法来打印rand_arr（如1e10）
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[5.434049e-04 2.783694e-04 4.245176e-04]
 [8.447761e-04 4.718856e-06 1.215691e-04]
 [6.707491e-04 8.258528e-04 1.367066e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [37]:
#将numpy数组a中打印的项数限制为最多6个元素
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [42]:
#打印完整的numpy数组a而不截断
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [51]:
#导入鸢尾属植物数据集，保持文本不变
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object',encoding='utf-8')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [54]:
#从前面问题中导入的一维鸢尾属植物数据集中提取文本列的物种
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None,encoding='utf-8')
#print(iris_1d)
print(iris_1d.shape)

# Solution:
species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [58]:
#通过省略鸢尾属植物数据集种类的文本字段，将一维鸢尾属植物数据集转换为二维数
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None,encoding='utf-8')

#第一种
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4])

#第二种
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [59]:
#求出鸢尾属植物萼片长度的平均值、中位数和标准差(第1列)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

#使用numpy函数
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [60]:
#创建一种标准化形式的鸢尾属植物间隔长度，其值正好介于0和1之间，这样最小值为0，最大值为1。
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
#第一种
S = (sepallength - Smin)/(Smax - Smin)
print(S)

#第二种
S = (sepallength - Smin)/sepallength.ptp()  # Thanks, David Ojeda!
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111